import type { Metadata } from 'next'
import './globals.css'
import { PropsWithChildren } from 'react'
import { Fredoka, Changa } from 'next/font/google'

const fontDisplay = Changa({ subsets: ['latin'] })
const fontBody = Fredoka({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-BR">
      <body
        className={`${fontDisplay.className} ${fontBody.className} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
